import type { Metadata } from "next";
import '../app/globals.css';
import '../app/page.css';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <main>
        {children}
      </main>
      </body>
    </html>
  );
}
